# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
- name: install tuned packages
  yum:
    name: "{{ tuned_packages | join(',') }}"
    state: present
    allow_downgrade: yes
  when: not offline_enable | default(False)
  become: yes

- name: install tuned packages - offline mode
  yum:
    name: "{{ offline_tuned_packages | join(',') }}"
    state: present
    allow_downgrade: yes
  when: offline_enable | default(False)
  become: yes

- name: setup isolated cores
  block:
    - name: find isolcpus value if applied as grub parameter
      set_fact:
        isol_cpus: "{{ additional_grub_params | regex_search('isolcpus=[0-9-,\n]*') | regex_replace('isolcpus=') }}"
    - name: change isolcpus tuned setting
      set_fact:
        tuned_vars: "{{ tuned_vars | regex_replace('isolated_cores=[0-9-,\n]*', 'isolated_cores={{ isol_cpus }}\n') }}"
  when: additional_grub_params is defined and additional_grub_params is search("isolcpus")

- name: copy tuned variables into the file
  copy:
    content: "{{ tuned_vars }}"
    dest: /etc/tuned/{{ tuned_profile }}-variables.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: set force_latency in realtime config
  blockinfile:
    path: /usr/lib/tuned/realtime/tuned.conf
    block: |
      [cpu]
      force_latency=-1
  when: tuned_force_latency_enable is defined and tuned_force_latency_enable
  become: yes

- name: apply tuned profile
  command: tuned-adm profile {{ tuned_profile }}
  changed_when: true
  become: yes

- name: get tuned CMDLINE
  command: awk -F'"' '/TUNED_BOOT_CMDLINE/ {print $2}' /etc/tuned/bootcmdline
  register: tuned_cmdline
  changed_when: false

- name: get current CMDLINE
  command: cat /proc/cmdline
  register: current_cmdline
  changed_when: false

# role `conditional_reboot` checks if `perform_reboot` is defined, is so machine is rebooted
- name: request reboot (will be performed by `conditional_reboot` role)
  set_fact:
    perform_reboot: "{{ perform_reboot|default([]) + [ 'tuned' ] }}"
  when: tuned_cmdline.stdout not in current_cmdline.stdout
